Repository jonkoops/matomo-tracker, pull requests merged in 2020-09, with the labels that each got.

#241 Make trackPageView params argument optional
  CHANGELOG.md
  packages/js/src/MatomoTracker.ts
Labels: enhancement

#242 Add 'pushInstuction' method to useMatomo
  CHANGELOG.md
  packages/react/src/types.ts
  packages/react/src/useMatomo.ts
Labels: bug

#243 Add documentation for the pushInstruction() function
  packages/react/README.md
Labels: documentation, enhancement

#236 Make siteId property required
  CHANGELOG.md
  packages/js/README.md
  packages/js/src/MatomoTracker.test.ts
  packages/js/src/MatomoTracker.ts
  packages/js/src/constants.ts
  packages/react/README.md
  packages/react/src/useMatomo.test.tsx
Labels: breaking change
